import type { Job, Candidate, AuditEntry, TriageResult } from "./types";

function rationale(
  verdict: TriageResult["verdict"],
  summary: string,
  hits: string[],
  misses: string[],
  flags: string[]
): TriageResult {
  return {
    verdict,
    summary,
    hits,
    misses,
    flags,
    confidence:
      verdict === "disqualify" ? 0.92 : verdict === "escalate" ? 0.81 : 0.66,
  };
}

export const JOB: Job = {
  id: "JOB-2847",
  title: "Senior Backend Engineer",
  team: "Platform / Payments",
  location: "San Francisco, CA",
  workMode: "Hybrid (3 days onsite)",
  level: "Senior (L5)",
  compRange: "$210k\u2013$260k base + equity",
  postedAt: "Mar 14, 2026",
  hiringManager: "Priya Shah",
  recruiter: "Marcus Chen (you)",
  description: `We\u2019re hiring a Senior Backend Engineer to join the Payments Platform team. You\u2019ll own services that move ~$4B/year in transaction volume and partner closely with product, ML, and SRE.

You\u2019ll lead designs for high-throughput, low-latency services. We expect strong distributed-systems judgment, comfort with on-call, and a track record of shipping in production environments.`,
  required: [
    "5+ years backend experience in production",
    "Strong proficiency in Go OR Python (we use both)",
    "Postgres, schema design, query optimization",
    "Distributed systems: queues, idempotency, consistency",
    "On-call experience in a payments / fintech / high-stakes domain",
    "Based in SF Bay Area or willing to relocate (hybrid required)",
  ],
  niceToHave: [
    "Kafka or equivalent event-streaming experience",
    "Exposure to PCI-DSS or SOC2 environments",
    "Open-source contributions",
    "Mentorship of junior engineers",
  ],
  hardDisqualifiers: [
    { id: "loc", label: "Outside US (no visa sponsorship for this req)" },
    {
      id: "exp",
      label: "Less than 4 years professional backend experience",
    },
    { id: "stack", label: "No Go AND no Python in last 3 years" },
    { id: "remote", label: "Remote-only (role is hybrid SF)" },
  ],
  softFlags: [
    {
      id: "hop",
      label: "Job hopping: 3+ roles under 18 months in last 5y",
    },
    { id: "gap", label: "Unexplained gap > 12 months" },
    { id: "junior", label: "Title regression / under-leveled for L5" },
    { id: "domain", label: "No fintech / high-stakes domain experience" },
  ],
};

export const CANDIDATES: Candidate[] = [
  {
    id: "c-001",
    name: "Aisha Okonkwo",
    headline: "Staff Engineer @ Stripe \u00b7 9y backend",
    location: "San Francisco, CA",
    relocate: false,
    yoe: 9,
    currentRole: "Staff Engineer, Payments Infrastructure",
    currentCompany: "Stripe",
    tenure: "4y 2mo",
    stack: ["Go", "Postgres", "Kafka", "gRPC", "K8s"],
    education: "BS Computer Science, Carnegie Mellon",
    summary:
      "Led the redesign of Stripe\u2019s idempotency layer. On-call rotation for 4 years. Mentors 6 ICs. Open-source contributions to sqlx and pgx.",
    receivedAt: "2h ago",
    source: "Referral (Priya S.)",
    triage: rationale(
      "escalate",
      "Strong match. Senior+ at a fintech peer with directly-relevant infra experience. Referral from HM.",
      [
        "9y backend",
        "Go + Postgres + Kafka all present",
        "Payments domain (Stripe)",
        "On-call leadership",
        "OSS contributions",
        "SF-based",
      ],
      [],
      []
    ),
  },
  {
    id: "c-002",
    name: "Daniel Roth",
    headline: "Senior Engineer @ Netflix \u00b7 7y backend",
    location: "Los Gatos, CA",
    relocate: false,
    yoe: 7,
    currentRole: "Senior Software Engineer, Streaming Platform",
    currentCompany: "Netflix",
    tenure: "3y 1mo",
    stack: ["Java", "Cassandra", "Kafka", "AWS"],
    education: "MS CS, Stanford",
    summary:
      "Owns playback-session services. Java-heavy background, no Go or Python in production in last 3 years per resume. Strong distributed-systems chops.",
    receivedAt: "5h ago",
    source: "LinkedIn",
    triage: rationale(
      "maybe",
      "Strong distributed-systems engineer but stack mismatch. Java-only in last 3 years; no Go/Python recent.",
      [
        "7y backend",
        "Distributed systems depth",
        "Kafka experience",
        "Bay Area",
      ],
      ["No Go in last 3y", "No Python in last 3y"],
      ["domain"]
    ),
  },
  {
    id: "c-003",
    name: "Priscilla Vance",
    headline: "Backend Engineer \u00b7 2.5y experience",
    location: "Austin, TX",
    relocate: true,
    yoe: 2.5,
    currentRole: "Software Engineer II",
    currentCompany: "Indeed",
    tenure: "1y 4mo",
    stack: ["Python", "Django", "MySQL", "Redis"],
    education: "BS CS, UT Austin",
    summary:
      "Strong Python and SQL fundamentals, ships well. Only 2.5 years professional experience \u2014 under the 4y bar for this req.",
    receivedAt: "8h ago",
    source: "Inbound (careers page)",
    triage: rationale(
      "disqualify",
      "Hard DQ: under the experience bar (2.5y vs 4y minimum). Otherwise promising \u2014 flag for L4 reqs.",
      ["Python solid", "Open to relocate"],
      ["Only 2.5y experience (hard DQ: <4y)"],
      []
    ),
    autoDQ: {
      rule: "exp",
      ruleLabel: "Less than 4 years professional backend experience",
      at: "8h ago",
    },
  },
  {
    id: "c-004",
    name: "Marcus Brennan",
    headline: "Engineering Manager \u00b7 11y \u00b7 Square",
    location: "Oakland, CA",
    relocate: false,
    yoe: 11,
    currentRole: "Engineering Manager, Risk",
    currentCompany: "Block (Square)",
    tenure: "2y 6mo",
    stack: ["Go", "Python", "Postgres", "Kafka", "Snowflake"],
    education: "BS EE, UC Berkeley",
    summary:
      "Was Staff IC for 6 years before moving into management 2.5 years ago. Manages 8 engineers on Risk Platform. Notes interest in returning to IC.",
    receivedAt: "12h ago",
    source: "Recruiter outreach",
    triage: rationale(
      "escalate",
      "Senior IC-to-EM-to-IC transition. Stack and domain are excellent. Worth a screen to confirm IC intent is genuine.",
      [
        "11y total",
        "Go + Python + Postgres + Kafka all present",
        "Payments-adjacent (Risk)",
        "SF Bay Area",
      ],
      [],
      ["Title regression (EM\u2192IC) \u2014 confirm motivation"]
    ),
  },
  {
    id: "c-005",
    name: "Yuki Tanaka",
    headline: "Senior Engineer \u00b7 Remote-only \u00b7 Tokyo",
    location: "Tokyo, Japan",
    relocate: false,
    yoe: 8,
    currentRole: "Senior Backend Engineer",
    currentCompany: "Mercari",
    tenure: "3y 8mo",
    stack: ["Go", "Postgres", "GCP", "Kubernetes"],
    education: "MS CS, University of Tokyo",
    summary:
      "Excellent technical match on paper. Based in Tokyo, marked remote-only. Role is hybrid SF and req does not sponsor visas.",
    receivedAt: "1d ago",
    source: "LinkedIn",
    triage: rationale(
      "disqualify",
      "Hard DQ: location + remote-only. Tokyo-based, no relocation, role requires hybrid SF.",
      ["Go + Postgres", "8y experience", "Strong technical signal"],
      [
        "Outside US (req does not sponsor)",
        "Remote-only (role is hybrid)",
      ],
      []
    ),
    autoDQ: {
      rule: "loc",
      ruleLabel: "Outside US (no visa sponsorship for this req)",
      at: "1d ago",
    },
  },
  {
    id: "c-006",
    name: "Elena Vasquez",
    headline: "Senior Backend \u00b7 6y \u00b7 Plaid",
    location: "San Francisco, CA",
    relocate: false,
    yoe: 6,
    currentRole: "Senior Backend Engineer",
    currentCompany: "Plaid",
    tenure: "2y 1mo",
    stack: ["Go", "Postgres", "Temporal", "Kafka"],
    education: "BS CS, UCLA",
    summary:
      "Builds bank-link services at Plaid. Direct fintech overlap. Strong on-call story (P0 oncall lead). Has spoken at GopherCon.",
    receivedAt: "1d ago",
    source: "Referral (Eng team)",
    triage: rationale(
      "escalate",
      "Direct fintech peer with all required signals. Public speaking suggests communication strength.",
      [
        "6y backend",
        "Go + Postgres + Kafka",
        "Fintech domain (Plaid)",
        "On-call lead",
        "SF-based",
        "Public speaker",
      ],
      [],
      []
    ),
  },
  {
    id: "c-007",
    name: "James Whitfield",
    headline: "Backend Engineer \u00b7 6y \u00b7 4 jobs in 5y",
    location: "San Jose, CA",
    relocate: false,
    yoe: 6,
    currentRole: "Backend Engineer",
    currentCompany: "Rippling",
    tenure: "8mo",
    stack: ["Python", "FastAPI", "Postgres", "Redis"],
    education: "BS CS, San Jose State",
    summary:
      "Tenures: Rippling 8mo, Brex 11mo, Affirm 14mo, Coinbase 1y 2mo, Wealthfront 1y 5mo. Strong stack match but tenure pattern is concerning.",
    receivedAt: "2d ago",
    source: "Inbound",
    triage: rationale(
      "maybe",
      "Strong stack and seniority match but flagged for tenure pattern: 4 roles under 18mo in last 5y crosses the threshold.",
      ["6y backend", "Python + Postgres", "Fintech domain"],
      [],
      ["Job hopping: 4 roles under 18mo in last 5y"]
    ),
  },
  {
    id: "c-008",
    name: "Sana Iqbal",
    headline: "Senior Engineer \u00b7 8y \u00b7 18mo gap",
    location: "Berkeley, CA",
    relocate: false,
    yoe: 8,
    currentRole: "Senior Backend Engineer",
    currentCompany: "Coinbase",
    tenure: "1y 11mo",
    stack: ["Go", "Postgres", "Kafka", "Terraform"],
    education: "BS CS, Stanford",
    summary:
      "Strong technical match. 18-month gap (Jan 2023 \u2013 Jul 2024). Resume notes \u2018caregiving sabbatical, returned via Path Forward returnship\u2019. Excellent recent work at Coinbase.",
    receivedAt: "2d ago",
    source: "Returnship program",
    triage: rationale(
      "escalate",
      "Strong match with explained gap (caregiving + returnship). All technical signals present. Returnship pipeline is a positive signal.",
      [
        "8y backend",
        "Go + Postgres + Kafka",
        "Fintech (Coinbase)",
        "Bay Area",
        "Gap is explained and contextualized",
      ],
      [],
      []
    ),
  },
  {
    id: "c-009",
    name: "Chad Pemberton",
    headline: "Full-stack Engineer \u00b7 5y \u00b7 React-heavy",
    location: "Brooklyn, NY",
    relocate: false,
    yoe: 5,
    currentRole: "Senior Full-Stack Engineer",
    currentCompany: "Datadog",
    tenure: "2y 3mo",
    stack: ["TypeScript", "Node.js", "React", "Postgres"],
    education: "BS CS, NYU",
    summary:
      "Primarily frontend/full-stack. Backend exposure is Node.js/TypeScript only. No Go or Python in production. NYC-based, will not relocate.",
    receivedAt: "2d ago",
    source: "LinkedIn",
    triage: rationale(
      "disqualify",
      "Hard DQ: stack mismatch (no Go/Python) + remote/NY only. Backend depth is also limited.",
      ["5y experience", "Postgres exposure"],
      ["No Go", "No Python", "Frontend-leaning", "NY-only, no relocate"],
      []
    ),
    autoDQ: {
      rule: "stack",
      ruleLabel: "No Go AND no Python in last 3 years",
      at: "2d ago",
    },
  },
  {
    id: "c-010",
    name: "Rohit Nair",
    headline: "Senior SWE \u00b7 7y \u00b7 Uber",
    location: "Mountain View, CA",
    relocate: false,
    yoe: 7,
    currentRole: "Senior Software Engineer, Money",
    currentCompany: "Uber",
    tenure: "3y 4mo",
    stack: ["Go", "Postgres", "Kafka", "Cadence"],
    education: "BTech CS, IIT Bombay",
    summary:
      "Works on Uber Money (driver payouts). Direct payments-adjacent experience. Strong distributed-systems work on Cadence/Temporal.",
    receivedAt: "3d ago",
    source: "Referral (eng)",
    triage: rationale(
      "escalate",
      "Excellent technical and domain match. Payments-adjacent at Uber. All required signals.",
      [
        "7y backend",
        "Go + Postgres + Kafka",
        "Payments domain (Uber Money)",
        "Bay Area",
      ],
      [],
      []
    ),
  },
  {
    id: "c-011",
    name: "Hannah Kowalski",
    headline: "Backend Engineer \u00b7 4y \u00b7 Shopify",
    location: "Toronto, Canada",
    relocate: true,
    yoe: 4,
    currentRole: "Backend Engineer II",
    currentCompany: "Shopify",
    tenure: "2y",
    stack: ["Ruby", "Rails", "MySQL", "Kafka"],
    education: "BS CS, University of Waterloo",
    summary:
      "Solid mid-level. Rails-heavy stack. No Go/Python recent. Notes willingness to relocate to SF on TN visa.",
    receivedAt: "3d ago",
    source: "Inbound",
    triage: rationale(
      "disqualify",
      "Stack mismatch: Ruby/Rails primary, no Go or Python in last 3 years. Otherwise reasonable mid-level.",
      [
        "4y experience",
        "Open to relocate (TN eligible)",
        "Kafka exposure",
      ],
      ["No Go in last 3y", "No Python in last 3y", "Rails-primary"],
      []
    ),
    autoDQ: {
      rule: "stack",
      ruleLabel: "No Go AND no Python in last 3 years",
      at: "3d ago",
    },
  },
  {
    id: "c-012",
    name: "Tom\u00e1s Herrera",
    headline: "Senior Engineer \u00b7 6y \u00b7 Mercado Libre",
    location: "Buenos Aires, Argentina",
    relocate: true,
    yoe: 6,
    currentRole: "Senior Software Engineer",
    currentCompany: "Mercado Libre",
    tenure: "4y",
    stack: ["Go", "Python", "Postgres", "Kafka"],
    education: "Lic. en Sistemas, UBA",
    summary:
      "Excellent stack match. Latin America based, willing to relocate but req does not sponsor. Payments-adjacent (Mercado Pago).",
    receivedAt: "3d ago",
    source: "LinkedIn",
    triage: rationale(
      "disqualify",
      "Hard DQ: outside US, req does not sponsor. Strong technical profile \u2014 flag for roles that do sponsor.",
      [
        "Go + Python + Postgres + Kafka",
        "Payments domain",
        "6y experience",
      ],
      ["Outside US, no sponsorship on this req"],
      []
    ),
    autoDQ: {
      rule: "loc",
      ruleLabel: "Outside US (no visa sponsorship for this req)",
      at: "3d ago",
    },
  },
  {
    id: "c-013",
    name: "Beatrice Lin",
    headline: "Senior Engineer \u00b7 6y \u00b7 DoorDash",
    location: "San Francisco, CA",
    relocate: false,
    yoe: 6,
    currentRole: "Senior Software Engineer",
    currentCompany: "DoorDash",
    tenure: "1y 8mo",
    stack: ["Python", "Postgres", "Kafka", "Kubernetes"],
    education: "BS CS, UC San Diego",
    summary:
      "Solid match. Works on Dasher payments. No Go but strong Python. SF-based, on-call experience.",
    receivedAt: "3d ago",
    source: "LinkedIn",
    triage: rationale(
      "maybe",
      "Solid all-around match. Python-only (no Go) which is acceptable per JD (\u2018Go OR Python\u2019).",
      [
        "6y backend",
        "Python + Postgres + Kafka",
        "Payments-adjacent",
        "On-call experience",
        "SF",
      ],
      ["No Go (acceptable \u2014 JD says \u2018Go OR Python\u2019)"],
      []
    ),
  },
  {
    id: "c-014",
    name: "Andre Klosterman",
    headline: "Architect \u00b7 14y \u00b7 IBM",
    location: "Austin, TX",
    relocate: true,
    yoe: 14,
    currentRole: "Software Architect",
    currentCompany: "IBM",
    tenure: "5y 2mo",
    stack: ["Java", "Spring", "Oracle", "WebSphere"],
    education: "MS CS, UT Austin",
    summary:
      "Senior, but stack is enterprise-Java with no Go/Python. Tenure-heavy at IBM. Open to relocate.",
    receivedAt: "4d ago",
    source: "Inbound",
    triage: rationale(
      "disqualify",
      "Hard DQ: no Go/Python in last 3 years. Enterprise-Java background is a poor fit for the platform.",
      ["14y experience", "Open to relocate"],
      ["No Go", "No Python", "Enterprise-Java only"],
      []
    ),
    autoDQ: {
      rule: "stack",
      ruleLabel: "No Go AND no Python in last 3 years",
      at: "4d ago",
    },
  },
  {
    id: "c-015",
    name: "Felicia Park",
    headline: "Senior Engineer \u00b7 5y \u00b7 Robinhood",
    location: "Palo Alto, CA",
    relocate: false,
    yoe: 5,
    currentRole: "Senior Backend Engineer",
    currentCompany: "Robinhood",
    tenure: "1y 7mo",
    stack: ["Python", "Go", "Postgres", "Kafka"],
    education: "BS CS, MIT",
    summary:
      "Strong match. Trading platform backend. Both Go and Python in production. PCI-DSS environment exposure.",
    receivedAt: "4d ago",
    source: "Recruiter outreach",
    triage: rationale(
      "escalate",
      "Strong all-signals match with bonus PCI-DSS exposure. Direct fintech.",
      [
        "5y backend",
        "Go + Python + Postgres + Kafka",
        "Fintech (Robinhood)",
        "PCI-DSS exposure",
        "Bay Area",
      ],
      [],
      []
    ),
  },
  {
    id: "c-016",
    name: "Vikram Subramanian",
    headline: "Senior Engineer \u00b7 7y \u00b7 6mo gap",
    location: "San Mateo, CA",
    relocate: false,
    yoe: 7,
    currentRole: "Senior Backend Engineer",
    currentCompany: "Affirm",
    tenure: "10mo",
    stack: ["Python", "Postgres", "Redis", "DynamoDB"],
    education: "MS CS, Georgia Tech",
    summary:
      "Strong Python, no Go. Short 6-month gap mid-2024 (no explanation). Currently at Affirm \u2014 direct fintech.",
    receivedAt: "4d ago",
    source: "LinkedIn",
    triage: rationale(
      "maybe",
      "Solid match. Python-only is acceptable. 6-month gap is under threshold but worth a question.",
      [
        "7y backend",
        "Python + Postgres",
        "Fintech (Affirm)",
        "SF Bay Area",
      ],
      ["No Go (acceptable)"],
      ["6mo gap mid-2024 (under 12mo threshold)"]
    ),
  },
  {
    id: "c-017",
    name: "Olivia Tremblay",
    headline: "Senior Engineer \u00b7 8y \u00b7 Cloudflare",
    location: "Remote (Vermont)",
    relocate: false,
    yoe: 8,
    currentRole: "Senior Systems Engineer",
    currentCompany: "Cloudflare",
    tenure: "3y",
    stack: ["Go", "Rust", "Postgres", "Kafka"],
    education: "BS CS, McGill",
    summary:
      "Outstanding technical profile. Remote-only (Vermont), role is hybrid SF. Will not relocate per cover letter.",
    receivedAt: "5d ago",
    source: "Inbound",
    triage: rationale(
      "disqualify",
      "Hard DQ: remote-only, role is hybrid SF. Strong profile \u2014 flag for any future remote reqs.",
      [
        "8y backend",
        "Go + Postgres + Kafka",
        "Distributed systems depth",
      ],
      ["Remote-only (role is hybrid SF)"],
      []
    ),
    autoDQ: {
      rule: "remote",
      ruleLabel: "Remote-only (role is hybrid SF)",
      at: "5d ago",
    },
  },
  {
    id: "c-018",
    name: "Kenji Watanabe",
    headline: "Senior Engineer \u00b7 6y \u00b7 Square",
    location: "San Francisco, CA",
    relocate: false,
    yoe: 6,
    currentRole: "Senior Software Engineer, Cash App",
    currentCompany: "Block (Cash App)",
    tenure: "2y 5mo",
    stack: ["Kotlin", "Go", "Postgres", "Kafka"],
    education: "BS CS, UCSD",
    summary:
      "Cash App backend. Kotlin-primary with significant Go work. Direct payments. SF-based.",
    receivedAt: "5d ago",
    source: "Referral",
    triage: rationale(
      "escalate",
      "Strong match. Cash App = direct payments domain. Go + Kotlin in production.",
      [
        "6y backend",
        "Go + Postgres + Kafka",
        "Payments domain (Cash App)",
        "SF",
        "Referral",
      ],
      [],
      []
    ),
  },
];

export const AUDIT_LOG_SEED: AuditEntry[] = [
  {
    type: "auto-dq",
    candidateId: "c-003",
    at: "8h ago",
    rule: "exp",
    ruleLabel: "Less than 4 years professional backend experience",
    reviewer: "system",
    confidence: 0.94,
  },
  {
    type: "auto-dq",
    candidateId: "c-005",
    at: "1d ago",
    rule: "loc",
    ruleLabel: "Outside US (no visa sponsorship for this req)",
    reviewer: "system",
    confidence: 0.99,
  },
  {
    type: "auto-dq",
    candidateId: "c-009",
    at: "2d ago",
    rule: "stack",
    ruleLabel: "No Go AND no Python in last 3 years",
    reviewer: "system",
    confidence: 0.88,
  },
  {
    type: "auto-dq",
    candidateId: "c-011",
    at: "3d ago",
    rule: "stack",
    ruleLabel: "No Go AND no Python in last 3 years",
    reviewer: "system",
    confidence: 0.91,
  },
  {
    type: "auto-dq",
    candidateId: "c-012",
    at: "3d ago",
    rule: "loc",
    ruleLabel: "Outside US (no visa sponsorship for this req)",
    reviewer: "system",
    confidence: 0.99,
  },
  {
    type: "auto-dq",
    candidateId: "c-014",
    at: "4d ago",
    rule: "stack",
    ruleLabel: "No Go AND no Python in last 3 years",
    reviewer: "system",
    confidence: 0.96,
  },
  {
    type: "auto-dq",
    candidateId: "c-017",
    at: "5d ago",
    rule: "remote",
    ruleLabel: "Remote-only (role is hybrid SF)",
    reviewer: "system",
    confidence: 0.93,
  },
  {
    type: "override",
    candidateId: "c-007",
    at: "2d ago",
    from: "disqualify",
    to: "maybe",
    note: "Tenure pattern flagged but candidate is 6y senior; talked to HM, worth a screen.",
    reviewer: "Marcus Chen",
  },
  {
    type: "flagged",
    candidateId: "c-003",
    at: "8h ago",
    note: "Low-confidence DQ flagged for review \u2014 candidate has 2.5y but strong signals. Confirmed: still under bar.",
    reviewer: "Marcus Chen",
  },
];
